
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrivateLabelLite.Data.DataEntities
{

using System;
    using System.Collections.Generic;
    
public partial class CompanyOrder
{

    public decimal CompanyId { get; set; }

    public decimal RecordId { get; set; }

    public Nullable<System.DateTime> Created { get; set; }

    public string CreatedBy { get; set; }

    public string SalesOrderId { get; set; }



    public virtual Company Company { get; set; }

    public virtual OrderHeader OrderHeader { get; set; }

}

}
