
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrivateLabelLite.Data.DataEntities
{

using System;
    using System.Collections.Generic;
    
public partial class OrderHeader
{

    public OrderHeader()
    {

        this.CompanyOrder = new HashSet<CompanyOrder>();

        this.OrderLine = new HashSet<OrderLine>();

    }


    public string OrderNumber { get; set; }

    public Nullable<System.DateTime> OrderDate { get; set; }

    public string OrderType { get; set; }

    public string EndUserName { get; set; }

    public string EndUserEmail { get; set; }

    public Nullable<decimal> TotalSalesPrice { get; set; }

    public string Status { get; set; }

    public string Domain { get; set; }

    public string CurrencySymbol { get; set; }

    public string CurrencyCode { get; set; }

    public Nullable<System.DateTime> LastUpdated { get; set; }

    public string OrderJson { get; set; }

    public string PONumber { get; set; }



    public virtual ICollection<CompanyOrder> CompanyOrder { get; set; }

    public virtual ICollection<OrderLine> OrderLine { get; set; }

}

}
