
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrivateLabelLite.Data.DataEntities
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    public decimal Id { get; set; }

    public string Sku { get; set; }

    public string SkuName { get; set; }

    public string ManufacturerPartNumber { get; set; }

    public string Article { get; set; }

    public string VendorMapId { get; set; }

    public string ProductType { get; set; }

    public Nullable<int> QtyMin { get; set; }

    public Nullable<int> QtyMax { get; set; }

    public Nullable<System.DateTime> LastUpdated { get; set; }

}

}
