
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrivateLabelLite.Data.DataEntities
{

using System;
    using System.Collections.Generic;
    
public partial class SubscriptionSummaryDetail
{

    public string OrderNumber { get; set; }

    public string VendorId { get; set; }

    public string VendorName { get; set; }

    public string SKU { get; set; }

    public string SkuName { get; set; }

    public string Quantity { get; set; }

    public string Article { get; set; }

    public string PaymentMethod { get; set; }

    public string EndCustomerName { get; set; }

    public string EndCustomerEmail { get; set; }

    public string Company { get; set; }

    public string OrderSource { get; set; }

    public string UnitPrice { get; set; }

    public string CurrencySymbol { get; set; }

    public string CurrencyCode { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public string LineStatus { get; set; }

    public string Domain { get; set; }

    public string MsSubscriptionId { get; set; }

    public string MicrosoftId { get; set; }

    public string SubscriptionHistoryJson { get; set; }

    public System.Guid SubscriptionId { get; set; }

    public string MappingStatus { get; set; }

    public Nullable<double> SalesPrice { get; set; }

    public Nullable<double> MarkUpPercentage { get; set; }

    public Nullable<double> SeatLimit { get; set; }

    public string TaxStatus { get; set; }

    public Nullable<System.DateTime> SeatLimitStartTime { get; set; }

    public Nullable<System.DateTime> SeatLimitEndTime { get; set; }

    public Nullable<int> SeatCounter { get; set; }

    public Nullable<double> TemporarySeatLimit { get; set; }

}

}
